vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /images/user
            upload_destination: "%kernel.project_dir%/public/images/user"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        posts_image:
            uri_prefix: /images/posts
            upload_destination: "%kernel.project_dir%/public/images/posts"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
